//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://netlogistik.winforstpro.com/wfpnetservicewcfdemo/service.svc")]
        public string webservice {
            get {
                return ((string)(this["webservice"]));
            }
            set {
                this["webservice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Zürichholz AG")]
        public string webfirma {
            get {
                return ((string)(this["webfirma"]));
            }
            set {
                this["webfirma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xPolver-ZHH")]
        public string uebergabewebfirma {
            get {
                return ((string)(this["uebergabewebfirma"]));
            }
            set {
                this["uebergabewebfirma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://xpprd.polver.ch")]
        public string client_endpoint {
            get {
                return ((string)(this["client_endpoint"]));
            }
            set {
                this["client_endpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0.0")]
        public string polverinterfaceversion {
            get {
                return ((string)(this["polverinterfaceversion"]));
            }
            set {
                this["polverinterfaceversion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wfpro-zhh")]
        public string polverusername {
            get {
                return ((string)(this["polverusername"]));
            }
            set {
                this["polverusername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("la0818zh")]
        public string polverpassword {
            get {
                return ((string)(this["polverpassword"]));
            }
            set {
                this["polverpassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mail_from {
            get {
                return ((string)(this["mail_from"]));
            }
            set {
                this["mail_from"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mail_to {
            get {
                return ((string)(this["mail_to"]));
            }
            set {
                this["mail_to"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string smtp_host {
            get {
                return ((string)(this["smtp_host"]));
            }
            set {
                this["smtp_host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string smtp_port {
            get {
                return ((string)(this["smtp_port"]));
            }
            set {
                this["smtp_port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string smtp_user {
            get {
                return ((string)(this["smtp_user"]));
            }
            set {
                this["smtp_user"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string smtp_pw {
            get {
                return ((string)(this["smtp_pw"]));
            }
            set {
                this["smtp_pw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\tmp\\0_Entwicklung\\20170601_Schnittstelle_ZHH\\20170802\\ConsoleApplication1\\dict" +
            "nlhs.txt")]
        public string dictionaryhs {
            get {
                return ((string)(this["dictionaryhs"]));
            }
            set {
                this["dictionaryhs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string password {
            get {
                return ((string)(this["password"]));
            }
            set {
                this["password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UploadUser")]
        public string username {
            get {
                return ((string)(this["username"]));
            }
            set {
                this["username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\tmp\\0_Entwicklung\\20170601_Schnittstelle_ZHH\\20170802\\ConsoleApplication1\\dict" +
            "nlha.txt")]
        public string dictionaryha {
            get {
                return ((string)(this["dictionaryha"]));
            }
            set {
                this["dictionaryha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\tmp\\0_Entwicklung\\20170601_Schnittstelle_ZHH\\20170802\\ConsoleApplication1\\dict" +
            "nlgkl.txt")]
        public string dictionarygkl {
            get {
                return ((string)(this["dictionarygkl"]));
            }
            set {
                this["dictionarygkl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\tmp\\0_Entwicklung\\20170601_Schnittstelle_ZHH\\20170802\\ConsoleApplication1\\ZHH_" +
            "SYNC_LOG.txt")]
        public string logs {
            get {
                return ((string)(this["logs"]));
            }
            set {
                this["logs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\tmp\\0_Entwicklung\\20170601_Schnittstelle_ZHH\\20170802\\ConsoleApplication1\\dict" +
            "contacts.txt")]
        public string dictionarycontacts {
            get {
                return ((string)(this["dictionarycontacts"]));
            }
            set {
                this["dictionarycontacts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pathtmpdocs {
            get {
                return ((string)(this["pathtmpdocs"]));
            }
            set {
                this["pathtmpdocs"] = value;
            }
        }
    }
}
